# Generated by Django 5.0.4 on 2024-06-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='user',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
