FROM node:20-alpine

WORKDIR /app

COPY package.json .

# Install any needed packages specified in requirements.txt
RUN npm install

# Copy the rest of the application code
COPY . .

EXPOSE 3000

CMD ["npm","run","dev"]
